// Generated by CoffeeScript 1.10.0
(function() {
  var SemverCmpBase, SemverCmpPre;

  SemverCmpBase = require("./semver-cmp-base");

  SemverCmpPre = require("./semver-cmp-pre");

  module.exports = {
    split: SemverCmpBase.split,
    cmp: SemverCmpBase.cmp,
    cmppre: SemverCmpPre.cmppre,
    lt: function(versionA, versionB) {
      return 0 > this.cmp(versionA, versionB);
    },
    lte: function(versionA, versionB) {
      return 0 >= this.cmp(versionA, versionB);
    },
    eq: function(versionA, versionB) {
      return 0 === this.cmp(versionA, versionB);
    },
    gt: function(versionA, versionB) {
      return 0 < this.cmp(versionA, versionB);
    },
    gte: function(versionA, versionB) {
      return 0 <= this.cmp(versionA, versionB);
    }
  };

}).call(this);
