// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = (function() {
    return {
      split: function(version) {
        var i, ref, release, result, segments;
        if ((ref = typeof version) !== "string" && ref !== "number") {
          throw new TypeError("version must be string or number");
        }
        segments = version.toString().split("-");
        release = segments[0].split(".");
        result = (function() {
          var j, results;
          results = [];
          for (i = j = 0; j < 3; i = ++j) {
            results.push(+release[i] || 0);
          }
          return results;
        })();
        if (segments[1]) {
          result[3] = segments[1];
        }
        return result;
      },
      cmp: function(versionA, versionB) {
        var a, b, i, j;
        a = this.split(versionA);
        b = this.split(versionB);
        for (i = j = 0; j < 3; i = ++j) {
          if (a[i] !== b[i]) {
            return (a[i] > b[i] ? 1 : -1);
          }
        }
        if (a[3] || b[3]) {
          return (b[3] && !a[3] ? 1 : -1);
        }
        return 0;
      },
      lt: function(versionA, versionB) {
        return 0 > this.cmp(versionA, versionB);
      },
      gte: function(versionA, versionB) {
        return 0 <= this.cmp(versionA, versionB);
      }
    };
  })();

}).call(this);
