// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = (function() {
    return {
      split: function(version) {
        var extras, i, ref, result, segments;
        if ((ref = typeof version) !== "string" && ref !== "number") {
          throw new TypeError("version must be string or number");
        }
        version = version.toString();
        segments = version.split(".");
        result = (function() {
          var j, results;
          results = [];
          for (i = j = 0; j < 3; i = ++j) {
            results.push(+segments[i] || 0);
          }
          return results;
        })();
        extras = segments.slice(3);
        if (extras.length) {
          result[3] = extras.join(".");
        }
        return result;
      },
      cmp: function(versionA, versionB) {
        var a, b, i, j;
        a = this.split(versionA);
        b = this.split(versionB);
        for (i = j = 0; j < 3; i = ++j) {
          if (a[i] !== b[i]) {
            return (a[i] > b[i] ? 1 : -1);
          }
        }
        return 0;
      },
      lt: function(versionA, versionB) {
        return 0 > this.cmp(versionA, versionB);
      },
      gte: function(versionA, versionB) {
        return 0 <= this.cmp(versionA, versionB);
      }
    };
  })();

}).call(this);
